# Generated by Django 5.2.5 on 2025-08-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_project_title_alter_project_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
